/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_learnandroid_slideconflict_HelloWorld */

#ifndef _Included_com_example_learnandroid_slideconflict_HelloWorld
#define _Included_com_example_learnandroid_slideconflict_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_learnandroid_slideconflict_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_learnandroid_slideconflict_HelloWorld_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
